/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.UInterfaces;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author daasa
 */
public class MundoLiterario extends javax.swing.JFrame implements KeyListener {
    private Theme darkTheme = new Theme(new Color(0, 0, 51), new Color(255, 255, 255), new Color(100, 100, 100));
    private Theme lightTheme = new Theme(new Color(255, 255, 255), new Color(0, 0, 0), new Color(200, 200, 200));
    private ImageIcon sunIcon = new ImageIcon(getClass().getResource("/proyectofinal/UInterfaces/resources/sun.png"));
    private ImageIcon moonIcon = new ImageIcon(getClass().getResource("/proyectofinal/UInterfaces/resources/moon.png"));
    private boolean isDarkMode = false;  // Variable para rastrear el tema actual
    
    private int playerX = 50; // posición inicial X del jugador
    private int playerY = 50; // posición inicial Y del jugador
    private JLabel playerDot; // representa el jugador en el mapa

    
private int entryX = 150; // posición X ficticia de entrada
private int entryY = 150; // posición Y ficticia de entrada


    int xMouse, yMouse;

    /**
     * Creates new form Inicio
     */
    public MundoLiterario() {
        initComponents();
        applyTheme(lightTheme);
        jLabel6.setIcon(moonIcon);  // Establece el ícono inicial del sol
        
        // Inicializar el punto del jugador
        playerDot = new JLabel();
        playerDot.setBounds(playerX, playerY, 10, 10);
        playerDot.setOpaque(true);
        playerDot.setBackground(Color.RED);
        jPanel1.add(playerDot); // Añadir el punto al jPanel1
        this.addKeyListener(this); // Agregar el KeyListener a tu JFrame
        
        this.setFocusable(true); // Permitir que tu JFrame reciba eventos del teclado
        setFocusable(true); // Permite que el JFrame reciba eventos de teclado
    }
    private void applyTheme(Theme theme) {
        jPanel1.setBackground(theme.backgroundColor);
        jLabel2.setForeground(theme.textColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitButton = new Clases.PanelRound();
        changeMode = new Clases.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        minimizeWindow = new Clases.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        panelNivel5 = new Clases.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelNivel2 = new Clases.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        panelNivel3 = new Clases.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelNivel4 = new Clases.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        panelNivel1 = new Clases.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelNivel10 = new Clases.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        panelNivel7 = new Clases.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        panelNivel8 = new Clases.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        panelNivel6 = new Clases.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        panelNivel9 = new Clases.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 51, 51));
        exitButton.setPreferredSize(new java.awt.Dimension(25, 25));
        exitButton.setRoundBottomLeft(100);
        exitButton.setRoundBottomRight(100);
        exitButton.setRoundTopLeft(100);
        exitButton.setRoundTopRight(100);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        changeMode.setBackground(new java.awt.Color(102, 0, 153));
        changeMode.setPreferredSize(new java.awt.Dimension(25, 25));
        changeMode.setRoundBottomLeft(100);
        changeMode.setRoundBottomRight(100);
        changeMode.setRoundTopLeft(100);
        changeMode.setRoundTopRight(100);
        changeMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeModeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeModeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeModeMouseEntered(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/UInterfaces/resources/moon.png"))); // NOI18N

        javax.swing.GroupLayout changeModeLayout = new javax.swing.GroupLayout(changeMode);
        changeMode.setLayout(changeModeLayout);
        changeModeLayout.setHorizontalGroup(
            changeModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeModeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        changeModeLayout.setVerticalGroup(
            changeModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeModeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        minimizeWindow.setBackground(java.awt.Color.gray);
        minimizeWindow.setPreferredSize(new java.awt.Dimension(25, 25));
        minimizeWindow.setRoundBottomLeft(100);
        minimizeWindow.setRoundBottomRight(100);
        minimizeWindow.setRoundTopLeft(100);
        minimizeWindow.setRoundTopRight(100);
        minimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeWindowMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout minimizeWindowLayout = new javax.swing.GroupLayout(minimizeWindow);
        minimizeWindow.setLayout(minimizeWindowLayout);
        minimizeWindowLayout.setHorizontalGroup(
            minimizeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        minimizeWindowLayout.setVerticalGroup(
            minimizeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(1247, Short.MAX_VALUE)
                .addComponent(minimizeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minimizeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("y pon a prueba tus conocimientos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        panelNivel5.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel5.setRoundBottomLeft(100);
        panelNivel5.setRoundBottomRight(100);
        panelNivel5.setRoundTopLeft(100);
        panelNivel5.setRoundTopRight(100);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("5");

        javax.swing.GroupLayout panelNivel5Layout = new javax.swing.GroupLayout(panelNivel5);
        panelNivel5.setLayout(panelNivel5Layout);
        panelNivel5Layout.setHorizontalGroup(
            panelNivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNivel5Layout.setVerticalGroup(
            panelNivel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel1.add(panelNivel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 470, 40, 40));

        panelNivel2.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel2.setRoundBottomLeft(100);
        panelNivel2.setRoundBottomRight(100);
        panelNivel2.setRoundTopLeft(100);
        panelNivel2.setRoundTopRight(100);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2");

        javax.swing.GroupLayout panelNivel2Layout = new javax.swing.GroupLayout(panelNivel2);
        panelNivel2.setLayout(panelNivel2Layout);
        panelNivel2Layout.setHorizontalGroup(
            panelNivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelNivel2Layout.setVerticalGroup(
            panelNivel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 610, -1, 40));

        panelNivel3.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel3.setRoundBottomLeft(100);
        panelNivel3.setRoundBottomRight(100);
        panelNivel3.setRoundTopLeft(100);
        panelNivel3.setRoundTopRight(100);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3");

        javax.swing.GroupLayout panelNivel3Layout = new javax.swing.GroupLayout(panelNivel3);
        panelNivel3.setLayout(panelNivel3Layout);
        panelNivel3Layout.setHorizontalGroup(
            panelNivel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNivel3Layout.setVerticalGroup(
            panelNivel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel1.add(panelNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 610, -1, 40));

        panelNivel4.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel4.setRoundBottomLeft(100);
        panelNivel4.setRoundBottomRight(100);
        panelNivel4.setRoundTopLeft(100);
        panelNivel4.setRoundTopRight(100);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4");

        javax.swing.GroupLayout panelNivel4Layout = new javax.swing.GroupLayout(panelNivel4);
        panelNivel4.setLayout(panelNivel4Layout);
        panelNivel4Layout.setHorizontalGroup(
            panelNivel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNivel4Layout.setVerticalGroup(
            panelNivel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel1.add(panelNivel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, -1, 40));

        panelNivel1.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel1.setRoundBottomLeft(100);
        panelNivel1.setRoundBottomRight(100);
        panelNivel1.setRoundTopLeft(100);
        panelNivel1.setRoundTopRight(100);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1");

        javax.swing.GroupLayout panelNivel1Layout = new javax.swing.GroupLayout(panelNivel1);
        panelNivel1.setLayout(panelNivel1Layout);
        panelNivel1Layout.setHorizontalGroup(
            panelNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelNivel1Layout.setVerticalGroup(
            panelNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 610, 40, 40));

        panelNivel10.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel10.setRoundBottomLeft(100);
        panelNivel10.setRoundBottomRight(100);
        panelNivel10.setRoundTopLeft(100);
        panelNivel10.setRoundTopRight(100);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("10");

        javax.swing.GroupLayout panelNivel10Layout = new javax.swing.GroupLayout(panelNivel10);
        panelNivel10.setLayout(panelNivel10Layout);
        panelNivel10Layout.setHorizontalGroup(
            panelNivel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNivel10Layout.setVerticalGroup(
            panelNivel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel10Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelNivel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, -1, 40));

        panelNivel7.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel7.setRoundBottomLeft(100);
        panelNivel7.setRoundBottomRight(100);
        panelNivel7.setRoundTopLeft(100);
        panelNivel7.setRoundTopRight(100);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("7");

        javax.swing.GroupLayout panelNivel7Layout = new javax.swing.GroupLayout(panelNivel7);
        panelNivel7.setLayout(panelNivel7Layout);
        panelNivel7Layout.setHorizontalGroup(
            panelNivel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        panelNivel7Layout.setVerticalGroup(
            panelNivel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jPanel1.add(panelNivel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, -1, 40));

        panelNivel8.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel8.setRoundBottomLeft(100);
        panelNivel8.setRoundBottomRight(100);
        panelNivel8.setRoundTopLeft(100);
        panelNivel8.setRoundTopRight(100);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("8");

        javax.swing.GroupLayout panelNivel8Layout = new javax.swing.GroupLayout(panelNivel8);
        panelNivel8.setLayout(panelNivel8Layout);
        panelNivel8Layout.setHorizontalGroup(
            panelNivel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        panelNivel8Layout.setVerticalGroup(
            panelNivel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelNivel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, 40));

        panelNivel6.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel6.setRoundBottomLeft(100);
        panelNivel6.setRoundBottomRight(100);
        panelNivel6.setRoundTopLeft(100);
        panelNivel6.setRoundTopRight(100);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("6");

        javax.swing.GroupLayout panelNivel6Layout = new javax.swing.GroupLayout(panelNivel6);
        panelNivel6.setLayout(panelNivel6Layout);
        panelNivel6Layout.setHorizontalGroup(
            panelNivel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNivel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNivel6Layout.setVerticalGroup(
            panelNivel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        jPanel1.add(panelNivel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, -1, 40));

        panelNivel9.setBackground(new java.awt.Color(255, 51, 153));
        panelNivel9.setRoundBottomLeft(100);
        panelNivel9.setRoundBottomRight(100);
        panelNivel9.setRoundTopLeft(100);
        panelNivel9.setRoundTopRight(100);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("9");

        javax.swing.GroupLayout panelNivel9Layout = new javax.swing.GroupLayout(panelNivel9);
        panelNivel9.setLayout(panelNivel9Layout);
        panelNivel9Layout.setHorizontalGroup(
            panelNivel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel9Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        panelNivel9Layout.setVerticalGroup(
            panelNivel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNivel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jPanel1.add(panelNivel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 130, -1, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/UInterfaces/resources/mapaWorld 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 410, 730));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel14.setText("Selecciona los niveles de menor a mayor ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(jLabel15);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 870, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setBackground(new Color(128, 0, 0));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setBackground(Color.red);
    }//GEN-LAST:event_exitButtonMouseExited

    private void changeModeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModeMouseEntered
        changeMode.setBackground(new Color(90, 0, 138));
    }//GEN-LAST:event_changeModeMouseEntered

    private void changeModeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModeMouseExited
        changeMode.setBackground(new Color(102, 0, 153));
    }//GEN-LAST:event_changeModeMouseExited

    private void minimizeWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseEntered
        minimizeWindow.setBackground(new Color(64, 64, 64));
    }//GEN-LAST:event_minimizeWindowMouseEntered

    private void minimizeWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseExited
        minimizeWindow.setBackground(Color.gray);
    }//GEN-LAST:event_minimizeWindowMouseExited

    private void minimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeWindowMouseClicked
        this.setState(Frame.ICONIFIED);  // Minimiza la ventana
    }//GEN-LAST:event_minimizeWindowMouseClicked

    private void changeModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeModeMouseClicked
        if (isDarkMode) {
            applyTheme(lightTheme);  // Cambiar al tema claro
            jLabel6.setIcon(moonIcon);  // Mostrar la luna
        } else {
            applyTheme(darkTheme);   // Cambiar al tema oscuro
            jLabel6.setIcon(sunIcon);  // Mostrar el sol
        }
        isDarkMode = !isDarkMode;  // Invertir el estado del tema
    }//GEN-LAST:event_changeModeMouseClicked
             

    public void testPlayerMovementAndEntryDetection() {
    // Mover el jugador a una posición alejada de la entrada
    playerX = 10;
    playerY = 10;
    playerDot.setLocation(playerX, playerY);
    
    // Mover el jugador hacia la entrada en pasos de 10 unidades
    while (playerX != entryX || playerY != entryY) {
        if (playerX < entryX) {
            playerX += 10;
        } else if (playerX > entryX) {
            playerX -= 10;
        }

        if (playerY < entryY) {
            playerY += 10;
        } else if (playerY > entryY) {
            playerY -= 10;
        }

        playerDot.setLocation(playerX, playerY);
        System.out.println("Player position: " + playerX + ", " + playerY);

        // Si el jugador está en la entrada, mostrar un mensaje
        if (isPlayerAtEntry()) {
            System.out.println("Player has reached the entry!");
            break;
        }

        // Agrega un pequeño retraso para visualizar el movimiento del jugador
        try {
            Thread.sleep(500);  // Esperar 500 milisegundos (0.5 segundos) antes del siguiente movimiento
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* ... Código existente ... */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MundoLiterario ml = new MundoLiterario();
            ml.setVisible(true);
            ml.testPlayerMovementAndEntryDetection();
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.PanelRound changeMode;
    private Clases.PanelRound exitButton;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Clases.PanelRound minimizeWindow;
    private Clases.PanelRound panelNivel1;
    private Clases.PanelRound panelNivel10;
    private Clases.PanelRound panelNivel2;
    private Clases.PanelRound panelNivel3;
    private Clases.PanelRound panelNivel4;
    private Clases.PanelRound panelNivel5;
    private Clases.PanelRound panelNivel6;
    private Clases.PanelRound panelNivel7;
    private Clases.PanelRound panelNivel8;
    private Clases.PanelRound panelNivel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()) {
                case KeyEvent.VK_UP:
                    playerY -= 10;
                    break;
                case KeyEvent.VK_DOWN:
                    playerY += 10;
                    break;
                case KeyEvent.VK_LEFT:
                    playerX -= 10;
                    break;
                case KeyEvent.VK_RIGHT:
                    playerX += 10;
                    break;
            }
            // Actualizar posición del punto del jugador
            playerDot.setLocation(playerX, playerY);
            
            // Lógica para mostrar el JOptionPane al intentar acceder a un nivel
            if (isPlayerAtEntry()) {
                String answer = JOptionPane.showInputDialog("Responda la pregunta para acceder al nivel:");
                if (answer != null && answer.equals("respuesta correcta")) {
                    // El jugador respondió correctamente y puede acceder al nivel
                } else {
                    // Respuesta incorrecta
                    JOptionPane.showMessageDialog(null, "Respuesta incorrecta!");
                }
            }
        }
   
    // Función para verificar si el jugador está en la posición de entrada
    private boolean isPlayerAtEntry() {
        return playerX == entryX && playerY == entryY;
    }


    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
